config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: { registrations: 'users/registrations' }
  root 'recipes#index', as: 'home'

  get 'about' => 'pages#about'

  resources :unit_systems
  resources :states
  resources :units
  resources :unit_kinds
  resources :unit_converts
  resources :recipes do
    resources :coments
    resources :ingredients
  end
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/coment.rb
class Coment < ApplicationRecord
  belongs_to :recipe
  belongs_to :user
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  belongs_to :recipe
  belongs_to :unit
  belongs_to :user
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_many :coments
  has_many :ingredients
end

app/models/state.rb
class State < ApplicationRecord
  belongs_to :unit_system
  validates :name, presence: true
end

app/models/unit.rb
class Unit < ApplicationRecord
  belongs_to :unit_system
  belongs_to :unit_kind

  validates :name, presence: true

  def self.obj_to_hash(filter)
    h = Hash.new
    Unit.where(filter).each do |o|
      h[o.id] = o.name + ' ['+o.unit_kind.name+']'
    end
    return h
  end
end

app/models/unit_convert.rb
class UnitConvert < ApplicationRecord
  belongs_to :unit_from, class_name: 'Unit', :validate => true
  belongs_to :unit_to, class_name: 'Unit', :foreign_key => 'unit_to_id', :validate => true

  validates :ratio, presence: true
  #validates_with UnitConvertValidator

  def self.do_convert(unit_from, unit_system_to_id, value)
    unit_name = unit_from.name
    system_from_id = unit_from.unit_system_id

    # Если используется одна система единиц, возвращаем исходные значения
    if system_from_id == unit_system_to_id
      return value, unit_name, nil
    end
    # Выбираем прямые преобразования
    converts = Array.new
    UnitConvert.where('unit_from_id=? and unit_to_id in (select id from units where unit_system_id=? and unit_kind_id=?)', unit_from.id,unit_system_to_id,unit_from.unit_kind).each do |u|
      converts.push( {ratio: u.ratio, unit_name: u.unit_to.name } )
    end
    # Добавляем обратные преобразования
    UnitConvert.where('unit_to_id=? and unit_from_id in (select id from units where unit_system_id=? and unit_kind_id=?)', unit_from.id,unit_system_to_id,unit_from.unit_kind).each do |u|
      converts.push( {ratio: 1.0/u.ratio, unit_name: u.unit_from.name } )
    end

    # Если нет переобразования, возвращаем исходные значения
    if converts.length == 0
      return value, unit_name, nil
    end

    # Ищем приемлемое значение (не слишком маленькое и не слишком большое)
    # Если условие не выполнено, будет выведенно постеднее найденое значение
    v = value
    converts.each do |c|
      v = c[:ratio]*value
      unit_name = c[:unit_name]
      if v > 0.5 and v < 1000
        break
      end
    end

    return v, unit_name, converts
  end
end

class UnitConvertValidator < ActiveModel::Validator
  def validate(context)
    if context.unit_from.unit_kind != context.unit_to.unit_kind
      context.errors.add :base, 'классы единиц должны быть одинаковы'
    end
  end
end

app/models/unit_kind.rb
class UnitKind < ApplicationRecord
  validates :name, presence: true
end

app/models/unit_system.rb
class UnitSystem < ApplicationRecord
  validates :title, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence:true
  validates :state_id, presence: true
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about

  end
end

app/controllers/units_controller.rb
class UnitsController < ApplicationController
  def index
    @units = Unit.order(:name).all
  end

  def new
    @unit = Unit.new
  end

  def show
    @unit = Unit.find(params[:id])
  end

  def create
    @unit = Unit.new(unit_params)

    if(@unit.save)
      redirect_to units_path
    else
      render 'new'
    end
  end

  def edit
    @unit = Unit.find(params[:id])
  end

  def update
    @unit = Unit.find(params[:id])
    if(@unit.update(unit_params))
      redirect_to units_path
    else
      render 'edit'
    end
  end

  def destroy
    @unit = Unit.find(params[:id])
    @unit.destroy

    redirect_to units_path
  end

  private def unit_params
    params.require(:unit).permit(:name, :symbol, :unit_system_id, :unit_kind_id )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/coments_helper.rb
module ComentsHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/states_helper.rb
module StatesHelper
end

app/helpers/unit_converts_helper.rb
module UnitConvertsHelper
end

app/helpers/unit_kind_helper.rb
module UnitKindHelper
end

app/helpers/unit_systems_helper.rb
module UnitSystemsHelper
end

app/helpers/units_helper.rb
module UnitsHelper
end

app/views/units/_edit_new.html.erb
<% if @unit.errors.any? %>
  <% @unit.errors.full_messages.each do |msg| %>
    <div class="alert alert-danger"><%= msg %></div>
  <% end %>
<% end %>

<p>Название<br>
  <%= @form.text_field(:name, {:class => 'form-control'} )%>
</p>
<p>Обозначение<br>
  <%= @form.text_field(:symbol, {:class => 'form-control'} )%>
</p>
<p>
  Система единиц<br>
  <%= @form.collection_select(:unit_system_id,  UnitSystem.all.order(:title), :id, :title, prompt: true)%>
</p>
<p>
  Допускает конвертацию<br>
  <%= @form.collection_select(:unit_kind_id,  UnitKind.all.order(:name), :id, :name, prompt: true)%>
</p>

app/views/units/edit.html.erb
<h3>Изменить единицу</h3>
<%= form_for( :unit, url: unit_path(@unit), method: :patch) do |f| %>
  <% @form=f %>
  <%= render 'edit_new' %>

  <p>
    <%= f.submit('Запомнить', {:class => 'btn btn-warning'}) %>
    <%= link_to 'Отмена', units_path, :class => 'btn btn-outline-primary'  %>
  </p>
<% end %>

app/views/units/index.html.erb
<div>
  <p> Единицы      <span class="btn btn-outline-primary" href="#"><%= link_to "Добавить", new_unit_path %></span>
  </p>
</div>
<table>
  <tr>
    <th width="50%">Название</th>
    <th width="20%">Обозначение</th>
    <th>Класс</th>
    <th>Система</th>
  </tr>
  <% @units.order(:unit_system).each do |unit| %>
    <tr>
      <td><%= link_to unit.name, unit_path(unit) %></td>
      <td> <%= unit.symbol %> </td>
      <td> <%= unit.unit_kind.name %> </td>
      <td> <%= unit.unit_system.title %> </td>
    </tr>
  <% end %>
</table>

app/views/units/new.html.erb
<h3>Добавить единицу</h3>
<%= form_for( :unit, url: units_path) do |f| %>
  <% @form = f %>
  <%= render 'edit_new' %>

  <p>  <%= f.submit('Запомнить', {:class => 'btn btn-outline-primary'}) %>
    <%= link_to 'Отмена', units_path, :class => 'btn btn-outline-primary'  %>
  </p>
<% end %>

app/views/units/show.html.erb
<h4>Единица</h4>
<h5><%= @unit.name %></h5>
<p><%= @unit.symbol %></p>
<p><%= @unit.unit_system.title %></p>
<br>
<p>
  <%= link_to 'Редактировать', edit_unit_path(@unit), :class=>'btn btn-warning' %>
  <%= link_to 'Удалить', unit_path(@unit), method: :delete, data: {confirm: "Удалить?"}, :class=>'btn btn-danger' %>
  <%= link_to 'Отмена', units_path, :class => 'btn btn-outline-primary'  %>
</p>